[package]
name = "FunctionTracer"
version = "0.1.0"
edition = "2018"
authors = ["Alessandro Mantovani"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fork = "0.1.18"
nix = "0.9.0"
